opt_in_rules:
 - sorted_imports

disabled_rules:
 - void_function_in_ternary
 - todo
 - trailing_whitespace
 - redundant_string_enum_value

line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

nesting:
  type_level:
    warning: 2
    error: 3
