name: FastLane Try Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-for-pr:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4.1.4

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Fastlane try_build
        run: bundle exec fastlane try_build

      - run: echo "::notice::${{ github.actor }} ran Fastlane try_build (${{ job.status }})."
